version: '3.0'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
      - smtp
    depends_on:
      - mongo    
    environment:
      - MAIL_URL=smtp://smtp:25
      - ROOT_URL=http://espinr.ddns.net
      - METEOR_SETTINGS= '{"mqtt_broker":"mqtt://espinr.ddns.net","mqtt_port":1883,"openTrackBaseUri":"http://purl.org/athletics"}'
      - MONGO_URL=mongodb://mongo:27017/meteor
    container_name: pbest_app

  mongo:
    image: mongo:3.7
    command: mongod --storageEngine=wiredTiger
    volumes:
      - './data:/data/db'
    container_name: pbest_mongo

  smtp:
    image: namshi/smtp:latest
    container_name: pbest_smtp

